#!/bin/bash

cat <<EOF

----

Polkit rule creation Script

This script creates Policiy kit entries
to allow a user in the wheel group (sudoers) to
execute certain commands without a password prompt.

Use this tool only if you are aware of the possible consequences.

-----
EOF

read -p "How should your rule be called? " rulename
read -p "What program name do you want to execute without a password prompt? " progname

sudo cat > /etc/polkit-1/rules.d/$rulename.rules <<EOF
polkit.addRule(function(action, subject) {
  if (action.id == $progname && subject.local && subject.active && subject.isInGroup(wheel)) {
      return polkit.Result.YES;
  }
});
EOF && cat <<EOF
Success!

Rule created.
EOF
